# Generated by Django 4.2.7 on 2023-11-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('id_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.games')),
            ],
        ),
        migrations.CreateModel(
            name='Lobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.games')),
                ('id_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chess.users')),
            ],
        ),
    ]
