# Generated by Django 4.2.7 on 2023-12-07 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_users_login_alter_lobbies_id_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobbies',
            name='id_users',
        ),
        migrations.AddField(
            model_name='lobbies',
            name='id_host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='chess.users'),
        ),
        migrations.AddField(
            model_name='lobbies',
            name='id_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player', to='chess.users'),
        ),
    ]
